export type ResourceFormat = "Article" | "Assessment" | "Worksheet" | "Guide";
export type Lang = "en" | "id";

export type Resource = {
  id: string;
  slug: string | null;
  title: string;
  titleId?: string;
  description: string;
  descriptionId?: string;
  time: string;
  format: ResourceFormat;
  languages: Lang[];
  gated: boolean;
  topics: string[];
  keywords?: string[];
};

export type Topic = {
  slug: string;
  title: string;
  description: string;
  icon: string;
};

export const TOPICS: Topic[] = [
  {
    slug: "cross-cultural",
    title: "Cross-Cultural",
    description: "Navigating cultural difference — how to read, adapt, and lead across contexts without losing yourself.",
    icon: "M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2 2 2 0 012 2v2.945M8 3.935V5.5A2.5 2.5 0 0010.5 8h.5a2 2 0 012 2 2 2 0 104 0 2 2 0 012-2h1.064M15 20.488V18a2 2 0 012-2h3.064M21 12a9 9 0 11-18 0 9 9 0 0118 0z",
  },
  {
    slug: "leadership",
    title: "Leadership",
    description: "Frameworks and practices for leading with clarity, influence, and conviction — at every level.",
    icon: "M9 20l-5.447-2.724A1 1 0 013 16.382V5.618a1 1 0 011.447-.894L9 7m0 13l6-3m-6 3V7m6 10l4.553 2.276A1 1 0 0021 18.382V7.618a1 1 0 00-.553-.894L15 4m0 13V4m0 0L9 7",
  },
  {
    slug: "team-facilitation",
    title: "Team & Facilitation",
    description: "Tools for leading teams well — facilitation, conflict, health, feedback, and keeping groups moving forward.",
    icon: "M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0z",
  },
  {
    slug: "personal-development",
    title: "Personal Development",
    description: "Becoming more of who you are — mindset, habits, self-awareness, and sustainable growth.",
    icon: "M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253",
  },
  {
    slug: "thinking-tools",
    title: "Thinking Tools",
    description: "Frameworks that sharpen how you think, decide, and solve problems — especially under pressure.",
    icon: "M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z",
  },
  {
    slug: "faith-calling",
    title: "Faith & Calling",
    description: "Staying rooted in what matters most — the biblical foundations of leadership, identity, and purpose.",
    icon: "M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z",
  },
  {
    slug: "self-care",
    title: "Self-Care & Resilience",
    description: "Protecting your wellbeing — burnout prevention, mental health, healthy rhythms, and personal sustainability for the long haul.",
    icon: "M14.828 14.828a4 4 0 01-5.656 0M21 12a9 9 0 11-18 0 9 9 0 0118 0zm-9-4a1 1 0 11-2 0 1 1 0 012 0zm0 8a1 1 0 11-2 0 1 1 0 012 0z",
  },
];

export const RESOURCES: Resource[] = [
  // ── CROSS-CULTURAL ─────────────────────────────────────────────────────────
  {
    id: "cultural-intelligence",
    slug: "cultural-intelligence",
    title: "Cultural Intelligence (CQ)",
    titleId: "Kecerdasan Budaya (CQ)",
    description: "Understand the four dimensions of Cultural Intelligence — and how to develop the capacity to function effectively in any cultural context.",
    descriptionId: "Pahami empat dimensi Kecerdasan Budaya — dan bagaimana mengembangkan kapasitas untuk berfungsi efektif dalam konteks budaya apa pun.",
    time: "15 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: false,
    topics: ["cross-cultural"],
    keywords: ["CQ", "cultural awareness", "cross-cultural competence", "adaptability", "global mindset", "cultural agility", "intercultural", "kecerdasan budaya"],
  },
  {
    id: "power-distance",
    slug: "power-distance",
    title: "Power Distance",
    titleId: "Jarak Kekuasaan",
    description: "How authority, hierarchy, and respect are perceived differently across cultures — and what that means for how you lead, communicate, and make decisions.",
    descriptionId: "Bagaimana otoritas, hierarki, dan rasa hormat dipersepsikan secara berbeda lintas budaya — dan apa artinya bagi cara Anda memimpin dan berkomunikasi.",
    time: "25 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: false,
    topics: ["cross-cultural", "leadership"],
    keywords: ["Hofstede", "PDI", "hierarchy", "boss", "status", "boss-subordinate", "obedience", "deference", "senior", "jarak kekuasaan"],
  },
  {
    id: "intercultural-communication",
    slug: "intercultural-communication",
    title: "Intercultural Communication",
    titleId: "Komunikasi Lintas Budaya",
    description: "High-context vs. low-context, direct vs. indirect — understanding how cultures communicate so you stop misreading the people you lead.",
    descriptionId: "Konteks tinggi vs. rendah, langsung vs. tidak langsung — memahami cara budaya berkomunikasi agar Anda tidak salah membaca orang yang Anda pimpin.",
    time: "15 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: false,
    topics: ["cross-cultural"],
    keywords: ["communication styles", "misunderstanding", "non-verbal", "silence", "indirect", "face", "honor", "shame", "explicit", "implicit", "komunikasi"],
  },
  {
    id: "time-and-culture",
    slug: "time-and-culture",
    title: "Your Time Is Not My Time",
    titleId: "Waktumu Bukan Waktuku",
    description: "Discover your time orientation and understand the four cultural logics that govern how teams treat deadlines, meetings, and relationships — then compare your logic with the culture you work with most.",
    descriptionId: "Temukan orientasi waktu Anda dan pahami empat logika budaya yang mengatur cara tim memperlakukan tenggat waktu, rapat, dan hubungan — lalu bandingkan dengan budaya yang paling sering Anda ajak bekerja.",
    time: "35 min",
    format: "Assessment",
    languages: ["en", "id"],
    gated: true,
    topics: ["cross-cultural", "team-facilitation"],
    keywords: ["monochronic", "polychronic", "deadlines", "punctuality", "meeting", "schedule", "time management", "waktu", "flexible time", "elastic time", "relationship time", "clock time"],
  },
  {
    id: "building-trust-cultures",
    slug: "building-trust-across-cultures",
    title: "Building Trust Across Cultures",
    titleId: "Membangun Kepercayaan Lintas Budaya",
    description: "How trust is formed, earned, and lost differently in high- and low-context cultures.",
    descriptionId: "Bagaimana kepercayaan dibentuk, diperoleh, dan hilang secara berbeda dalam budaya konteks tinggi dan rendah.",
    time: "25 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: true,
    topics: ["cross-cultural"],
    keywords: ["trust building", "rapport", "relationship", "reliability", "credibility", "cognitive trust", "affective trust", "kepercayaan", "trustworthy", "earn trust", "loyalty"],
  },
  {
    id: "giving-feedback-across-cultures",
    slug: "giving-feedback-across-cultures",
    title: "Giving Feedback Across Cultures",
    titleId: "Memberikan Umpan Balik Lintas Budaya",
    description: "Why feedback lands so differently depending on cultural context — and a framework for giving honest, constructive feedback across high- and low-context cultures.",
    descriptionId: "Mengapa umpan balik diterima sangat berbeda tergantung konteks budaya — dan kerangka untuk memberikan umpan balik yang jujur dan konstruktif.",
    time: "40 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: false,
    topics: ["cross-cultural", "team-facilitation"],
    keywords: ["feedback", "criticism", "constructive criticism", "face saving", "honor", "shame", "indirect feedback", "correction", "critique", "performance review", "umpan balik"],
  },
  {
    id: "ladder-of-inference",
    slug: "ladder-of-inference",
    title: "The Ladder of Inference",
    titleId: "Tangga Inferensi",
    description: "Most conflicts and misunderstandings start at the top of the Ladder — where we act on beliefs formed from incomplete data. Learn to trace your thinking back to the ground floor.",
    descriptionId: "Sebagian besar konflik dimulai di puncak Tangga — di mana kita bertindak berdasarkan keyakinan dari data yang tidak lengkap. Pelajari cara menelusuri kembali pemikiran Anda.",
    time: "15 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: true,
    topics: ["thinking-tools", "cross-cultural"],
    keywords: ["Argyris", "assumptions", "mental models", "beliefs", "jumping to conclusions", "inference", "bias", "perception", "critical thinking", "tangga inferensi", "data", "interpret"],
  },
  {
    id: "understanding-high-context",
    slug: "understanding-high-context",
    title: "Understanding High-Context Cultures",
    titleId: "Memahami Budaya Konteks Tinggi",
    description: "How communication styles shape relationships — and what that means for cross-cultural teams.",
    descriptionId: "Bagaimana gaya komunikasi membentuk hubungan — dan apa artinya bagi tim lintas budaya.",
    time: "20 min",
    format: "Article",
    languages: ["en", "id"],
    gated: true,
    topics: ["cross-cultural"],
    keywords: ["Edward Hall", "low-context", "high context", "indirect communication", "reading between lines", "implicit", "collectivist", "relationship-first", "face", "unspoken", "konteks tinggi"],
  },
  {
    id: "returning-well",
    slug: "returning-well",
    title: "Returning Well: Life After Cross-Cultural Work",
    titleId: "Kembali dengan Baik: Kehidupan Setelah Pelayanan Lintas Budaya",
    description: "Processing the transition back to your home culture after long-term cross-cultural service.",
    descriptionId: "Memproses transisi kembali ke budaya asal Anda setelah pelayanan lintas budaya jangka panjang.",
    time: "30 min",
    format: "Article",
    languages: ["en", "id"],
    gated: true,
    topics: ["self-care", "personal-development", "cross-cultural"],
    keywords: ["reentry", "re-entry", "reverse culture shock", "furlough", "home assignment", "going home", "grief", "loss", "transition", "readjust", "debrief"],
  },
  // ── LEADERSHIP ─────────────────────────────────────────────────────────────
  {
    id: "leadership-altitudes",
    slug: "leadership-altitudes",
    title: "Leadership Altitudes",
    titleId: "Ketinggian Kepemimpinan",
    description: "Understand the five altitude levels of leadership — from Team Member to International Organization — and learn to lead with perspective, trust, and strategic clarity.",
    descriptionId: "Pahami lima tingkat ketinggian kepemimpinan — dari Anggota Tim hingga Organisasi Internasional — dan pelajari cara memimpin dengan perspektif, kepercayaan, dan kejelasan strategis.",
    time: "15 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: false,
    topics: ["leadership"],
    keywords: ["levels", "perspective", "strategic", "micromanagement", "delegation", "big picture", "zooming out", "organizational", "altitude", "macro", "micro", "scope", "elevation"],
  },
  {
    id: "servant-leadership",
    slug: "servant-leadership",
    title: "Servant Leadership",
    titleId: "Kepemimpinan Hamba",
    description: "The biblical model of leading from below. Why the greatest leaders serve first — and what that looks like in cross-cultural ministry and organisational life.",
    descriptionId: "Model alkitabiah memimpin dari bawah. Mengapa pemimpin terbesar melayani terlebih dahulu — dan seperti apa dalam pelayanan lintas budaya dan kehidupan organisasi.",
    time: "20 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: false,
    topics: ["leadership", "faith-calling"],
    keywords: ["Greenleaf", "Jesus", "serve", "service", "humility", "sacrificial", "kepemimpinan hamba", "bottom-up", "others-first", "biblical leadership", "washing feet", "empowerment"],
  },
  {
    id: "vision-casting",
    slug: "vision-casting",
    title: "Vision Casting",
    titleId: "Menebar Visi",
    description: "What compelling vision looks like — and how to communicate direction so clearly that people not only understand it, but move. Cross-cultural vision communication included.",
    descriptionId: "Seperti apa visi yang memikat — dan cara mengomunikasikan arah dengan begitu jelas sehingga orang tidak hanya memahaminya, tetapi bergerak. Termasuk komunikasi visi lintas budaya.",
    time: "25 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: false,
    topics: ["leadership"],
    keywords: ["vision statement", "mission", "direction", "inspire", "motivate", "clarity", "future", "purpose", "communicate vision", "visi", "narrative", "cast vision", "rally"],
  },
  {
    id: "managing-up",
    slug: "managing-up",
    title: "Managing Up",
    titleId: "Mengelola ke Atas",
    description: "How to lead your leader well — understanding their needs, communicating upward effectively, and building the kind of trust that creates space for your own leadership to flourish.",
    descriptionId: "Cara memimpin pemimpin Anda dengan baik — memahami kebutuhan mereka, berkomunikasi ke atas secara efektif, dan membangun kepercayaan yang memberi ruang bagi kepemimpinan Anda sendiri.",
    time: "15 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: false,
    topics: ["leadership"],
    keywords: ["boss", "manager", "superior", "upward communication", "influence", "relationship", "authority", "navigate", "senior leader", "mengelola atasan", "expectations", "align"],
  },
  {
    id: "raising-next-generation",
    slug: "raising-next-generation",
    title: "Raising Up the Next Generation",
    titleId: "Membesarkan Generasi Berikutnya",
    description: "The multiplication principle: how to identify, invest in, and release the next generation of leaders — drawn from the Paul-Timothy model and real-world practice.",
    descriptionId: "Prinsip multiplikasi: cara mengidentifikasi, berinvestasi, dan melepaskan generasi pemimpin berikutnya — berdasarkan model Paulus-Timotius dan praktik nyata.",
    time: "15 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: false,
    topics: ["leadership", "faith-calling"],
    keywords: ["mentoring", "discipleship", "succession", "multiplication", "invest", "Paul Timothy", "legacy", "coaching", "develop leaders", "generation", "generasi", "reproduce"],
  },
  {
    id: "storytelling-leadership",
    slug: "storytelling-leadership",
    title: "Storytelling for Leaders",
    titleId: "Bercerita untuk Pemimpin",
    description: "Data informs. Stories move. Learn the structure of a compelling leadership story — and how to use narrative to cast vision, build culture, and connect across cultural lines.",
    descriptionId: "Data memberi informasi. Cerita menggerakkan. Pelajari struktur kisah kepemimpinan yang memikat — dan cara menggunakan narasi untuk menebarkan visi dan membangun budaya.",
    time: "15 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: false,
    topics: ["leadership"],
    keywords: ["story", "narrative", "communicate", "persuade", "inspire", "anecdote", "illustration", "hook", "public speaking", "presentation", "bercerita", "storytelling"],
  },
  // ── TEAM & FACILITATION ────────────────────────────────────────────────────
  {
    id: "team-health",
    slug: "team-health",
    title: "Team Health Assessment",
    titleId: "Penilaian Kesehatan Tim",
    description: "How to diagnose the health of your team before problems become crises. Signs of dysfunction, markers of health, and practical steps toward a stronger team culture.",
    descriptionId: "Cara mendiagnosis kesehatan tim sebelum masalah menjadi krisis. Tanda-tanda disfungsi, penanda kesehatan, dan langkah praktis menuju budaya tim yang lebih kuat.",
    time: "15 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: false,
    topics: ["team-facilitation"],
    keywords: ["Lencioni", "dysfunction", "morale", "culture", "toxic", "assessment", "diagnosis", "healthy team", "team dynamics", "collaboration", "trust", "accountability"],
  },
  {
    id: "six-thinking-hats",
    slug: "six-thinking-hats",
    title: "Six Thinking Hats",
    titleId: "Enam Topi Berpikir",
    description: "Edward de Bono's framework for parallel thinking. Separate facts, emotions, caution, optimism, creativity, and process — so your team thinks together without conflict.",
    descriptionId: "Kerangka berpikir paralel Edward de Bono. Pisahkan fakta, emosi, kewaspadaan, optimisme, kreativitas, dan proses — agar tim Anda berpikir bersama tanpa konflik.",
    time: "15 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: false,
    topics: ["team-facilitation", "thinking-tools"],
    keywords: ["de Bono", "parallel thinking", "white hat", "red hat", "black hat", "yellow hat", "green hat", "blue hat", "brainstorming", "creativity", "meeting facilitation"],
  },
  {
    id: "red-light-green-light",
    slug: "red-light-green-light",
    title: "Red Light & Green Light Thinking",
    titleId: "Pemikiran Lampu Merah & Lampu Hijau",
    description: "A facilitation framework for separating creative idea generation (Green Light) from critical evaluation and decision-making (Red Light) — helping teams think more freely and decide more clearly.",
    descriptionId: "Kerangka fasilitasi untuk memisahkan generasi ide kreatif (Lampu Hijau) dari evaluasi kritis dan pengambilan keputusan (Lampu Merah) — membantu tim berpikir lebih bebas dan memutuskan lebih jelas.",
    time: "15 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: true,
    topics: ["team-facilitation", "thinking-tools"],
    keywords: ["brainstorming", "ideation", "creative thinking", "critical thinking", "evaluation", "divergent", "convergent", "facilitation", "ideas", "workshop", "generate ideas"],
  },
  {
    id: "conflict-resolution-multicultural",
    slug: "conflict-resolution",
    title: "Conflict Resolution in Multicultural Teams",
    titleId: "Resolusi Konflik dalam Tim Multikultural",
    description: "Why conflict looks different across cultures — and how to navigate it constructively.",
    descriptionId: "Mengapa konflik terlihat berbeda lintas budaya — dan cara menavigasinya secara konstruktif.",
    time: "15 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: true,
    topics: ["team-facilitation", "cross-cultural"],
    keywords: ["conflict", "resolution", "mediation", "disagreement", "confrontation", "harmony", "face", "peacemaking", "tension", "difficult conversations", "resolusi konflik", "argument"],
  },
  {
    id: "attention-retention",
    slug: "attention-retention",
    title: "Attention & Retention",
    titleId: "Perhatian & Retensi",
    description: "Understand how attention and retention work in adult learning. Apply evidence-based principles to design training that sticks — across any culture or context.",
    descriptionId: "Pahami cara kerja perhatian dan retensi dalam pembelajaran orang dewasa. Terapkan prinsip berbasis bukti untuk merancang pelatihan yang berkesan — di budaya dan konteks apa pun.",
    time: "15 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: true,
    topics: ["team-facilitation"],
    keywords: ["learning", "training", "adult learning", "teaching", "facilitation", "memory", "retention", "spaced repetition", "engagement", "education", "andragogy", "design training"],
  },
  {
    id: "debriefing-reflection",
    slug: "debriefing-reflection",
    title: "Debriefing & Reflection",
    titleId: "Debriefing & Refleksi",
    description: "Leaders who don't reflect repeat their mistakes. A structured approach to debriefing experiences — individually and with your team — so that every season produces learning.",
    descriptionId: "Pemimpin yang tidak berefleksi mengulangi kesalahan mereka. Pendekatan terstruktur untuk mendebrifing pengalaman — secara individu dan bersama tim — agar setiap musim menghasilkan pembelajaran.",
    time: "15 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: false,
    topics: ["team-facilitation", "personal-development"],
    keywords: ["review", "after action", "learning", "reflection", "journal", "process", "evaluate", "Kolb", "experiential learning", "debrief", "retrospective", "refleksi"],
  },
  {
    id: "above-below-the-line",
    slug: "above-below-the-line",
    title: "Above & Below the Line",
    titleId: "Di Atas & Di Bawah Garis",
    description: "Are you leading as a Victor or a Victim? Recognize reactive patterns — blame, excuse, denial — and choose ownership, accountability, and responsibility instead.",
    descriptionId: "Apakah Anda memimpin sebagai Victor atau Victim? Kenali pola reaktif — menyalahkan, beralasan, menyangkal — dan pilih kepemilikan, akuntabilitas, dan tanggung jawab.",
    time: "15 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: true,
    topics: ["team-facilitation", "personal-development"],
    keywords: ["accountability", "ownership", "responsibility", "blame", "victim", "victor", "excuse", "denial", "reactive", "proactive", "OAR", "response-ability", "choice"],
  },
  // ── PERSONAL DEVELOPMENT ───────────────────────────────────────────────────
  {
    id: "comfort-zone",
    slug: "escaping-the-comfort-zone",
    title: "Escaping the Comfort Zone",
    titleId: "Keluar dari Zona Nyaman",
    description: "Identify where your comfort zone ends and growth begins. Understand the four zones — Comfort, Fear, Learning, and Growth — and take steps toward meaningful change.",
    descriptionId: "Identifikasi di mana zona nyaman Anda berakhir dan pertumbuhan dimulai. Pahami empat zona — Nyaman, Takut, Belajar, dan Pertumbuhan — dan ambil langkah menuju perubahan yang bermakna.",
    time: "20 min",
    format: "Worksheet",
    languages: ["en", "id"],
    gated: false,
    topics: ["personal-development"],
    keywords: ["zone", "growth", "fear", "challenge", "stretch", "risk", "change", "courage", "step out", "safe", "uncomfortable", "zona nyaman", "dare"],
  },
  {
    id: "fixed-growth-mindset",
    slug: "fixed-growth-mindset",
    title: "Fixed vs. Growth Mindset",
    titleId: "Mentalitas Tetap vs. Berkembang",
    description: "Based on Carol Dweck's landmark research — compare how fixed and growth mindsets respond to challenges, obstacles, skills, effort, and the success of others. Then shift yours.",
    descriptionId: "Berdasarkan penelitian penting Carol Dweck — bandingkan cara mentalitas tetap dan berkembang merespons tantangan, hambatan, keterampilan, dan kesuksesan orang lain. Lalu ubah milik Anda.",
    time: "20 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: true,
    topics: ["personal-development"],
    keywords: ["Dweck", "mindset", "effort", "failure", "talent", "ability", "learn", "challenge", "resilience", "brain", "neuroplasticity", "mentalitas", "potential"],
  },
  {
    id: "smart-goals",
    slug: "smart-goals",
    title: "SMART Goals",
    titleId: "SMART Goals",
    description: "A five-part framework for setting goals that actually get done — Specific, Motivated, Achievable, Relevant, and Trackable. With built-in corrective actions: Clarify, Reframe, or Negotiate.",
    descriptionId: "Kerangka lima bagian untuk menetapkan tujuan yang benar-benar tercapai — Spesifik, Termotivasi, Dapat Dicapai, Relevan, dan Terukur. Dengan tindakan korektif bawaan.",
    time: "20 min",
    format: "Worksheet",
    languages: ["en", "id"],
    gated: true,
    topics: ["personal-development"],
    keywords: ["goals", "objective", "target", "planning", "motivation", "measurable", "specific", "achievable", "relevant", "time-bound", "tujuan", "goal setting", "action plan"],
  },
  {
    id: "overcoming-procrastination",
    slug: "overcoming-procrastination",
    title: "Overcoming Procrastination",
    titleId: "Mengatasi Penundaan",
    description: "Procrastination isn't laziness — it's usually fear, perfectionism, or overwhelm in disguise. A 5-step framework to identify your triggers, uncover root causes, and build momentum.",
    descriptionId: "Penundaan bukan kemalasan — biasanya rasa takut, perfeksionisme, atau kewalahan yang tersamar. Kerangka 5 langkah untuk mengidentifikasi pemicu, mengungkap akar penyebab, dan membangun momentum.",
    time: "30 min",
    format: "Worksheet",
    languages: ["en", "id"],
    gated: true,
    topics: ["personal-development"],
    keywords: ["delay", "avoidance", "lazy", "motivation", "productivity", "stuck", "paralyzed", "perfectionism", "overwhelm", "start", "momentum", "penundaan", "distraction"],
  },
  {
    id: "emotional-intelligence",
    slug: "emotional-intelligence",
    title: "Emotional Intelligence (EQ)",
    titleId: "Kecerdasan Emosional (EQ)",
    description: "Daniel Goleman's five components of EQ — self-awareness, self-regulation, motivation, empathy, and social skills — and why they determine your effectiveness as a leader.",
    descriptionId: "Lima komponen EQ Daniel Goleman — kesadaran diri, regulasi diri, motivasi, empati, dan keterampilan sosial — dan mengapa mereka menentukan efektivitas Anda sebagai pemimpin.",
    time: "15 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: false,
    topics: ["personal-development", "leadership"],
    keywords: ["Goleman", "EQ", "emotions", "self-awareness", "empathy", "social skills", "emotional regulation", "feelings", "self-management", "kecerdasan emosional", "regulate"],
  },
  {
    id: "johari-window",
    slug: "johari-window",
    title: "The Johari Window",
    titleId: "Jendela Johari",
    description: "A model for self-awareness and team trust. Map your Open, Blind, Hidden, and Unknown zones — and learn to grow through feedback and disclosure.",
    descriptionId: "Model untuk kesadaran diri dan kepercayaan tim. Petakan zona Terbuka, Buta, Tersembunyi, dan Tidak Dikenal Anda — dan pelajari cara bertumbuh melalui umpan balik dan keterbukaan.",
    time: "15 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: false,
    topics: ["personal-development"],
    keywords: ["Luft", "Ingham", "self-awareness", "blind spot", "feedback", "disclosure", "transparency", "trust", "open area", "hidden self", "jendela johari", "unknown"],
  },
  {
    id: "leaders-are-readers",
    slug: "leaders-are-readers",
    title: "Leaders Are Readers",
    titleId: "Pemimpin Adalah Pembaca",
    description: "Great leaders commit to continuous learning. Discover why reading is a cornerstone of effective leadership and how to build a sustainable reading habit.",
    descriptionId: "Pemimpin hebat berkomitmen pada pembelajaran berkelanjutan. Temukan mengapa membaca adalah landasan kepemimpinan efektif dan cara membangun kebiasaan membaca yang berkelanjutan.",
    time: "15 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: true,
    topics: ["personal-development"],
    keywords: ["reading", "books", "study", "library", "intellectual", "book list", "knowledge", "habits", "learning habit"],
  },
  {
    id: "identity-under-pressure",
    slug: "identity-under-pressure",
    title: "Identity Under Pressure",
    titleId: "Identitas di Bawah Tekanan",
    description: "Maintaining a grounded sense of self when living and leading between worlds.",
    descriptionId: "Mempertahankan rasa diri yang kuat saat hidup dan memimpin di antara dua dunia budaya.",
    time: "15 min",
    format: "Article",
    languages: ["en", "id"],
    gated: true,
    topics: ["faith-calling", "personal-development"],
    keywords: ["identity", "self-worth", "who am I", "belonging", "calling", "purpose", "self", "security", "rootedness", "worth", "value"],
  },
  {
    id: "four-stages-competence",
    slug: "four-stages-competence",
    title: "Four Stages of Competence",
    titleId: "Empat Tahap Kompetensi",
    description: "From not knowing what you don't know, to mastery so deep you no longer need to think. The Conscious Competence Model maps how we actually learn — and where you are in your growth journey right now.",
    descriptionId: "Dari tidak tahu apa yang tidak Anda ketahui, hingga penguasaan yang begitu dalam sehingga Anda tidak perlu lagi berpikir. Model ini memetakan bagaimana kita sebenarnya belajar.",
    time: "15 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: true,
    topics: ["personal-development"],
    keywords: ["unconscious incompetence", "conscious incompetence", "conscious competence", "unconscious competence", "learning", "mastery", "skill", "expertise", "beginner", "novice", "competency"],
  },
  // ── THINKING TOOLS ─────────────────────────────────────────────────────────
  {
    id: "decision-making",
    slug: "decision-making",
    title: "Decision Making Under Uncertainty",
    titleId: "Pengambilan Keputusan dalam Ketidakpastian",
    description: "Frameworks for making wise decisions when you don't have all the information — especially in ambiguous, cross-cultural leadership contexts.",
    descriptionId: "Kerangka untuk membuat keputusan bijak ketika Anda tidak memiliki semua informasi — terutama dalam konteks kepemimpinan lintas budaya yang ambigu.",
    time: "15 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: false,
    topics: ["thinking-tools", "leadership"],
    keywords: ["decisions", "choice", "ambiguity", "options", "risk", "uncertainty", "analysis", "wisdom", "discernment", "intuition", "data", "framework", "keputusan"],
  },
  {
    id: "cognitive-biases",
    slug: "cognitive-biases",
    title: "Cognitive Biases in Leadership",
    titleId: "Bias Kognitif dalam Kepemimpinan",
    description: "The mental shortcuts and blind spots that distort how every leader thinks — mapped and explained. Awareness is the first step toward clearer, more honest leadership.",
    descriptionId: "Jalan pintas mental dan titik buta yang mendistorsi cara setiap pemimpin berpikir — dipetakan dan dijelaskan. Kesadaran adalah langkah pertama menuju kepemimpinan yang lebih jelas dan jujur.",
    time: "15 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: false,
    topics: ["thinking-tools"],
    keywords: ["bias", "heuristic", "blind spot", "confirmation bias", "anchoring", "availability bias", "sunk cost", "groupthink", "perception", "thinking error", "logical fallacy", "cognitive error"],
  },
  {
    id: "disc",
    slug: "disc",
    title: "DISC Personality Profile",
    titleId: "Profil Kepribadian DISC",
    description: "Understand your behavioural style and how it shapes the way you lead, communicate, and collaborate across cultures.",
    descriptionId: "Pahami gaya perilaku Anda dan bagaimana itu membentuk cara Anda memimpin, berkomunikasi, dan berkolaborasi lintas budaya.",
    time: "35 min",
    format: "Assessment",
    languages: ["en", "id"],
    gated: false,
    topics: ["leadership", "cross-cultural", "personal-development"],
    keywords: ["personality", "dominant", "influencing", "steadiness", "compliance", "introvert", "extrovert", "behavior style", "temperament"],
  },
  {
    id: "5languages",
    slug: "5languages",
    title: "5 Languages of Appreciation",
    titleId: "5 Bahasa Penghargaan",
    description: "Discover how you give and receive care in your ministry team. Two parallel tests reveal your receiving and giving languages — and the gap between them.",
    descriptionId: "Temukan bagaimana Anda memberi dan menerima perhatian dalam tim Anda. Dua tes paralel mengungkap bahasa penerimaan dan pemberian Anda — serta kesenjangan di antara keduanya.",
    time: "25 min",
    format: "Assessment",
    languages: ["en", "id"],
    gated: false,
    topics: ["leadership", "team-facilitation", "cross-cultural"],
    keywords: ["appreciation", "recognition", "love languages", "Gary Chapman", "motivation", "team morale", "affirmation", "acknowledgment", "reward", "penghargaan", "care", "words of affirmation"],
  },
  {
    id: "three-thinking-styles",
    slug: "three-thinking-styles",
    title: "Three Thinking Styles",
    titleId: "Tiga Gaya Berpikir",
    description: "Discover whether you lead with Conceptual, Holistic, or Intuitional thinking — and how to work across all three.",
    descriptionId: "Temukan apakah Anda memimpin dengan pemikiran Konseptual, Holistik, atau Intuitif — dan cara bekerja di antara ketiganya.",
    time: "25 min",
    format: "Assessment",
    languages: ["en", "id"],
    gated: false,
    topics: ["thinking-tools"],
    keywords: ["thinking", "conceptual", "holistic", "intuition", "cognitive style", "how you think", "reasoning", "analytical", "creative", "systematic", "gaya berpikir", "problem solving"],
  },
  {
    id: "big-five",
    slug: "big-five",
    title: "The Big Five (OCEAN)",
    titleId: "Big Five (OCEAN)",
    description: "The most scientifically validated personality framework in the world — five dimensions that predict how you lead, collaborate, adapt, and grow across every culture.",
    descriptionId: "Kerangka kepribadian paling tervalidasi secara ilmiah di dunia — lima dimensi yang memprediksi cara Anda memimpin, berkolaborasi, beradaptasi, dan bertumbuh di setiap budaya.",
    time: "25 min",
    format: "Assessment",
    languages: ["en", "id"],
    gated: false,
    topics: ["personal-development", "leadership", "cross-cultural"],
    keywords: ["personality", "openness", "conscientiousness", "extraversion", "agreeableness", "neuroticism", "introvert", "extrovert", "temperament", "traits"],
  },

  // ── FAITH & CALLING ────────────────────────────────────────────────────────
  {
    id: "sabbath-leadership",
    slug: "sabbath-leadership",
    title: "The Sabbath Leader",
    titleId: "Pemimpin yang Beristirahat",
    description: "Why sustainable leaders build rhythms of Sabbath — and how to practise it in high-demand cross-cultural environments.",
    descriptionId: "Mengapa pemimpin yang berkelanjutan membangun ritme Sabat — dan bagaimana mempraktikkannya di lingkungan lintas budaya yang penuh tuntutan.",
    time: "25 min",
    format: "Assessment",
    languages: ["en", "id"],
    gated: true,
    topics: ["leadership", "self-care", "faith-calling"],
    keywords: ["rest", "sabbath rest", "rhythm", "restoration", "renewal", "ceasing", "pause", "stop", "sleep", "istirahat"],
  },
  {
    id: "leading-without-losing-faith",
    slug: "leading-without-losing-faith",
    title: "Leading Without Losing Your Faith",
    titleId: "Memimpin Tanpa Kehilangan Imanmu",
    description: "Maintaining spiritual rootedness when leadership demands are high and cultural confusion is real.",
    descriptionId: "Mempertahankan keberakaran rohani ketika tuntutan kepemimpinan tinggi dan kebingungan budaya nyata adanya.",
    time: "15 min",
    format: "Article",
    languages: ["en", "id"],
    gated: true,
    topics: ["faith-calling"],
    keywords: ["faith", "God", "spiritual", "belief", "doubt", "prayer", "calling", "disillusionment", "spiritual dryness", "iman"],
  },
  // ── RESILIENCE & MENTAL HEALTH ─────────────────────────────────────────────
  {
    id: "understanding-burnout",
    slug: "understanding-burnout",
    title: "Understanding Burnout",
    titleId: "Memahami Kelelahan",
    description: "The three types of burnout — overload, underchallenge, and neglect — and how to build the people, practices, and purpose that prevent it.",
    descriptionId: "Tiga jenis kelelahan — beban berlebih, kurang tantangan, dan diabaikan — dan cara membangun orang, praktik, dan tujuan yang mencegahnya.",
    time: "30 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: true,
    topics: ["personal-development", "faith-calling", "self-care"],
    keywords: ["stress", "exhaustion", "tired", "fatigue", "depletion", "overwork", "wellbeing", "Elijah", "recovery", "rest", "kelelahan", "frenetic", "worn out"],
  },
  {
    id: "relational-longevity",
    slug: "relational-longevity",
    title: "Relational Longevity",
    titleId: "Kelanggengan Relasional",
    description: "Why relational breakdown is the leading cause of premature departure — and how to build the interpersonal skills that keep teams together for the long haul.",
    descriptionId: "Mengapa kerusakan relasional adalah penyebab utama kepergian dini — dan bagaimana membangun keterampilan interpersonal yang menjaga tim tetap bersama dalam jangka panjang.",
    time: "25 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: true,
    topics: ["team-facilitation", "personal-development", "self-care"],
    keywords: ["relationships", "friendship", "trust", "connection", "loyalty", "attrition", "retention", "departure", "interpersonal", "relasi"],
  },
  {
    id: "emotional-safety-families",
    slug: "emotional-safety-families",
    title: "Emotional Safety for Families",
    titleId: "Keamanan Emosional untuk Keluarga",
    description: "Parental stress directly shapes children's wellbeing. How to build emotional safety at home — and model humility through relational repair.",
    descriptionId: "Stres orang tua secara langsung mempengaruhi kesejahteraan anak. Cara membangun keamanan emosional di rumah — dan memodelkan kerendahan hati melalui pemulihan relasional.",
    time: "30 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: true,
    topics: ["self-care", "personal-development", "faith-calling"],
    keywords: ["parenting", "children", "kids", "marriage", "home", "family stress", "spouse", "third culture kids", "TCK", "MK", "missionary kid", "family health"],
  },
  {
    id: "healthy-transitions",
    slug: "healthy-transitions",
    title: "Healthy Transitions",
    titleId: "Transisi yang Sehat",
    description: "The RAFT model for navigating re-entry, role change, or any major life transition — Reconciliation, Affirmation, Farewells, Think Ahead.",
    descriptionId: "Model RPPP untuk menavigasi kepulangan, perubahan peran, atau transisi besar dalam hidup: Rekonsiliasi, Peneguhan, Perpisahan, Persiapkan Masa Depan.",
    time: "20 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: true,
    topics: ["self-care", "personal-development", "cross-cultural"],
    keywords: ["change", "grief", "loss", "leaving", "moving", "goodbye", "furlough", "endings", "RAFT model", "role change", "reentry"],
  },
  {
    id: "psychological-first-aid",
    slug: "psychological-first-aid",
    title: "Psychological First Aid",
    titleId: "Pertolongan Pertama Psikologis",
    description: "Equipping leaders to support teammates in crisis. The RAPID model for immediate, compassionate intervention when things go wrong in the field.",
    descriptionId: "Membekali pemimpin untuk mendukung rekan tim dalam krisis. Model RAPID untuk intervensi segera dan penuh belas kasihan ketika hal-hal berjalan buruk di lapangan.",
    time: "15 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: true,
    topics: ["team-facilitation", "personal-development", "self-care"],
    keywords: ["trauma", "mental health", "anxiety", "depression", "crisis", "emergency", "support", "stress", "incident", "debriefing", "care"],
  },
  {
    id: "sustainable-pace",
    slug: "sustainable-pace",
    title: "Sustainable Pace",
    titleId: "Tempo yang Berkelanjutan",
    description: "Sabbath rhythms, personal health architecture, and the theology of rest. Practical resilience habits for leaders built to last.",
    descriptionId: "Ritme Sabat, arsitektur kesehatan pribadi, dan teologi istirahat. Kebiasaan ketahanan praktis bagi pemimpin yang dibangun untuk bertahan lama.",
    time: "25 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: true,
    topics: ["self-care", "personal-development", "faith-calling"],
    keywords: ["rest", "rhythm", "sabbath", "sustainable", "slow down", "pace", "resilience", "longevity", "wellbeing", "burnout prevention", "stamina", "tempo", "margin", "istirahat"],
  },
  // ── TEAM & FACILITATION (continued) ───────────────────────────────────────
  {
    id: "healthy-conflict",
    slug: "healthy-conflict",
    title: "Creating Healthy Conflict",
    titleId: "Menciptakan Konflik yang Sehat",
    description: "Conflict avoidance is the instinct. But conflict is the solution. Learn how to create the conditions for productive, trust-building conflict in multicultural teams.",
    descriptionId: "Menghindari konflik adalah naluri. Tapi konflik adalah solusinya. Pelajari cara menciptakan kondisi untuk konflik yang produktif dan membangun kepercayaan dalam tim multikultural.",
    time: "25 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: false,
    topics: ["team-facilitation", "cross-cultural"],
    keywords: ["conflict", "disagreement", "productive conflict", "healthy tension", "debate", "friction", "difficult conversations", "brave", "avoid conflict", "confrontation", "konflik", "safe space"],
  },
  // ── ASSESSMENTS (added) ──────────────────────────────────────────────────────
  {
    id: "enneagram",
    slug: "enneagram",
    title: "Enneagram Personality System",
    titleId: "Sistem Kepribadian Enneagram",
    description: "Explore the nine Enneagram types — each with distinct motivations, fears, and growth paths. Discover your type and how it shapes the way you lead, relate, and grow.",
    descriptionId: "Jelajahi sembilan tipe Enneagram — masing-masing dengan motivasi, ketakutan, dan jalur pertumbuhan yang berbeda. Temukan tipe Anda dan bagaimana itu membentuk cara Anda memimpin dan bertumbuh.",
    time: "30 min",
    format: "Assessment",
    languages: ["en", "id"],
    gated: false,
    topics: ["personal-development", "leadership", "cross-cultural"],
    keywords: ["personality", "nine types", "wing", "tritype", "ego fixation", "self-awareness", "temperament"],
  },
  {
    id: "16-personalities",
    slug: "16-personalities",
    title: "16 Personalities",
    titleId: "16 Kepribadian",
    description: "Based on Jungian typology — identify your personality type across four dimensions and discover how your preferences shape your leadership, relationships, and decision-making.",
    descriptionId: "Berdasarkan tipologi Jung — identifikasi tipe kepribadian Anda di empat dimensi dan temukan bagaimana preferensi Anda membentuk kepemimpinan dan pengambilan keputusan.",
    time: "25 min",
    format: "Assessment",
    languages: ["en", "id"],
    gated: false,
    topics: ["personal-development", "leadership"],
    keywords: ["mbti", "myers briggs", "myers-briggs", "introvert", "extrovert", "personality type", "infj", "infp", "intj", "intp", "enfj", "enfp", "entj", "entp", "istj", "isfj", "istp", "isfp", "estj", "esfj", "estp", "esfp", "temperament"],
  },
  {
    id: "wheel-of-life",
    slug: "wheel-of-life",
    title: "Wheel of Life",
    titleId: "Roda Kehidupan",
    description: "Assess your current balance across eight life domains — family, finance, health, ministry, spiritual, community, learning, and relaxation. Identify where you're thriving and where growth is needed.",
    descriptionId: "Nilai keseimbangan Anda saat ini di delapan domain kehidupan — keluarga, keuangan, kesehatan, pelayanan, spiritual, komunitas, pembelajaran, dan relaksasi.",
    time: "20 min",
    format: "Assessment",
    languages: ["en", "id"],
    gated: false,
    topics: ["personal-development", "self-care", "faith-calling"],
    keywords: ["balance", "holistic", "wellbeing", "life areas", "health", "rest", "burnout prevention", "whole person", "life review", "fulfillment"],
  },
  {
    id: "karunia-rohani",
    slug: "karunia-rohani",
    title: "Spiritual Gifts",
    titleId: "Karunia Rohani",
    description: "Identify your spiritual gifts and discover how your unique God-given abilities contribute to community, ministry, and Kingdom work.",
    descriptionId: "Temukan karunia rohani Anda dan bagaimana kemampuan unik yang Tuhan berikan berkontribusi pada komunitas, pelayanan, dan pekerjaan Kerajaan Allah.",
    time: "25 min",
    format: "Assessment",
    languages: ["en", "id"],
    gated: false,
    topics: ["faith-calling"],
    keywords: ["spiritual gifts", "gifting", "charism", "talents", "gift assessment", "gifts test", "charisma", "abilities", "God-given", "anointing"],
  },
  {
    id: "leaders-inner-life",
    slug: "leaders-inner-life",
    title: "The Leader's Inner Life",
    titleId: "Kehidupan Batin Pemimpin",
    description: "Why interior formation comes before outward effectiveness — and how to tend the part of you that sustains everything else.",
    descriptionId: "Mengapa pembentukan batin mendahului efektivitas luar — dan bagaimana merawat bagian dari diri Anda yang menopang segalanya.",
    time: "15 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: true,
    topics: ["faith-calling", "personal-development"],
    keywords: ["prayer", "soul", "spiritual formation", "interior life", "devotional", "quiet time", "solitude", "spiritual health", "contemplation", "heart"],
  },
  {
    id: "called-without-the-map",
    slug: "called-without-the-map",
    title: "Called Without the Map",
    titleId: "Dipanggil Tanpa Peta",
    description: "How God works through calling without revealing the full plan — and why stepping forward before you have clarity is often how clarity comes.",
    descriptionId: "Bagaimana Allah bekerja melalui panggilan tanpa mengungkapkan rencana penuh — dan mengapa melangkah maju sebelum ada kejelasan sering kali adalah cara kejelasan itu datang.",
    time: "15 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: true,
    topics: ["faith-calling"],
    keywords: ["calling", "vocation", "purpose", "direction", "uncertainty", "faith", "trust", "plan", "future", "Abraham", "discernment"],
  },
  {
    id: "discipline-of-silence",
    slug: "discipline-of-silence",
    title: "The Discipline of Silence",
    titleId: "Disiplin Keheningan",
    description: "In a world that is always on, intentional silence has become the rarest leadership discipline. Discover why God speaks in quiet - and how to build the practice into your life and your team.",
    descriptionId: "Di dunia yang selalu hidup, keheningan yang intentional telah menjadi disiplin kepemimpinan yang paling langka. Temukan mengapa Allah berbicara dalam ketenangan - dan bagaimana membangun praktik ini dalam hidup dan tim Anda.",
    time: "20 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: true,
    topics: ["faith-calling", "self-care", "leadership"],
    keywords: ["quiet", "prayer", "contemplation", "solitude", "stillness", "meditation", "listening", "rest", "noise", "pace", "retreat", "hening"],
  },
  {
    id: "calling-is-never-solo",
    slug: "calling-is-never-solo",
    title: "Calling Is Never Solo",
    titleId: "Panggilan Tak Pernah Sendirian",
    description: "Your calling is one thread in a much larger tapestry. How God builds through communities, teams, and generations — and what it means to steward your piece well.",
    descriptionId: "Panggilan Anda adalah satu benang dalam permadani yang jauh lebih besar. Bagaimana Allah membangun melalui komunitas, tim, dan generasi — dan apa artinya mengelola bagian Anda dengan baik.",
    time: "15 min",
    format: "Guide",
    languages: ["en", "id"],
    gated: true,
    topics: ["faith-calling", "leadership"],
    keywords: ["community", "together", "partnership", "team ministry", "calling", "body of Christ", "collaboration", "isolation", "alone"],
  },
];

export function getTopicResources(topicSlug: string): Resource[] {
  return RESOURCES.filter(r => r.topics.includes(topicSlug));
}

export function getTopicBySlug(slug: string): Topic | undefined {
  return TOPICS.find(t => t.slug === slug);
}

export const LANG_LABELS: Record<string, string> = {
  en: "EN",
  id: "ID",
};
