export type ResourceFormat = "Article" | "Assessment" | "Worksheet" | "Guide";
export type Lang = "en" | "id" | "nl";

export type Resource = {
  id: string;
  slug: string | null;
  title: string;
  titleId?: string;
  titleNl?: string;
  description: string;
  descriptionId?: string;
  descriptionNl?: string;
  time: string;
  format: ResourceFormat;
  languages: Lang[];
  gated: boolean;
  topics: string[];
};

export type Topic = {
  slug: string;
  title: string;
  description: string;
  icon: string;
};

export const TOPICS: Topic[] = [
  {
    slug: "cross-cultural",
    title: "Cross-Cultural",
    description: "Navigating cultural difference — how to read, adapt, and lead across contexts without losing yourself.",
    icon: "M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2 2 2 0 012 2v2.945M8 3.935V5.5A2.5 2.5 0 0010.5 8h.5a2 2 0 012 2 2 2 0 104 0 2 2 0 012-2h1.064M15 20.488V18a2 2 0 012-2h3.064M21 12a9 9 0 11-18 0 9 9 0 0118 0z",
  },
  {
    slug: "leadership",
    title: "Leadership",
    description: "Frameworks and practices for leading with clarity, influence, and conviction — at every level.",
    icon: "M9 20l-5.447-2.724A1 1 0 013 16.382V5.618a1 1 0 011.447-.894L9 7m0 13l6-3m-6 3V7m6 10l4.553 2.276A1 1 0 0021 18.382V7.618a1 1 0 00-.553-.894L15 4m0 13V4m0 0L9 7",
  },
  {
    slug: "team-facilitation",
    title: "Team & Facilitation",
    description: "Tools for leading teams well — facilitation, conflict, health, feedback, and keeping groups moving forward.",
    icon: "M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0z",
  },
  {
    slug: "personal-development",
    title: "Personal Development",
    description: "Becoming more of who you are — mindset, habits, self-awareness, and sustainable growth.",
    icon: "M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253",
  },
  {
    slug: "thinking-tools",
    title: "Thinking Tools",
    description: "Frameworks that sharpen how you think, decide, and solve problems — especially under pressure.",
    icon: "M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z",
  },
  {
    slug: "faith-calling",
    title: "Faith & Calling",
    description: "Staying rooted in what matters most — the biblical foundations of leadership, identity, and purpose.",
    icon: "M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z",
  },
  {
    slug: "self-care",
    title: "Self-Care & Resilience",
    description: "Protecting your wellbeing — burnout prevention, mental health, healthy rhythms, and personal sustainability for the long haul.",
    icon: "M14.828 14.828a4 4 0 01-5.656 0M21 12a9 9 0 11-18 0 9 9 0 0118 0zm-9-4a1 1 0 11-2 0 1 1 0 012 0zm0 8a1 1 0 11-2 0 1 1 0 012 0z",
  },
];

export const RESOURCES: Resource[] = [
  // ── CROSS-CULTURAL ─────────────────────────────────────────────────────────
  {
    id: "cultural-intelligence",
    slug: "cultural-intelligence",
    title: "Cultural Intelligence (CQ)",
    titleId: "Kecerdasan Budaya (CQ)",
    titleNl: "Culturele Intelligentie (CQ)",
    description: "Understand the four dimensions of Cultural Intelligence — and how to develop the capacity to function effectively in any cultural context.",
    descriptionId: "Pahami empat dimensi Kecerdasan Budaya — dan bagaimana mengembangkan kapasitas untuk berfungsi efektif dalam konteks budaya apa pun.",
    descriptionNl: "Begrijp de vier dimensies van Culturele Intelligentie — en hoe je het vermogen ontwikkelt om in elke culturele context effectief te functioneren.",
    time: "14 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["cross-cultural"],
  },
  {
    id: "power-distance",
    slug: "power-distance",
    title: "Power Distance",
    titleId: "Jarak Kekuasaan",
    titleNl: "Machtafstand",
    description: "How authority, hierarchy, and respect are perceived differently across cultures — and what that means for how you lead, communicate, and make decisions.",
    descriptionId: "Bagaimana otoritas, hierarki, dan rasa hormat dipersepsikan secara berbeda lintas budaya — dan apa artinya bagi cara Anda memimpin dan berkomunikasi.",
    descriptionNl: "Hoe autoriteit, hiërarchie en respect verschillend worden waargenomen — en wat dat betekent voor hoe je leidt, communiceert en beslissingen neemt.",
    time: "11 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["cross-cultural", "leadership"],
  },
  {
    id: "intercultural-communication",
    slug: "intercultural-communication",
    title: "Intercultural Communication",
    titleId: "Komunikasi Lintas Budaya",
    titleNl: "Interculturele Communicatie",
    description: "High-context vs. low-context, direct vs. indirect — understanding how cultures communicate so you stop misreading the people you lead.",
    descriptionId: "Konteks tinggi vs. rendah, langsung vs. tidak langsung — memahami cara budaya berkomunikasi agar Anda tidak salah membaca orang yang Anda pimpin.",
    descriptionNl: "Hoge-context vs. lage-context, direct vs. indirect — begrijp hoe culturen communiceren zodat je stopt met het verkeerd lezen van de mensen die je leidt.",
    time: "13 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["cross-cultural"],
  },
  {
    id: "time-and-culture",
    slug: "time-and-culture",
    title: "Time & Culture",
    titleId: "Waktu & Budaya",
    titleNl: "Tijd & Cultuur",
    description: "Monochronic vs. polychronic time — why your team treats deadlines, meetings, and relationships very differently, and how to lead across that gap.",
    descriptionId: "Waktu monokronik vs. polikronik — mengapa tim Anda memperlakukan tenggat waktu, rapat, dan hubungan sangat berbeda, dan cara memimpin di tengah perbedaan itu.",
    descriptionNl: "Monochronische vs. polychronische tijd — waarom je team deadlines, vergaderingen en relaties heel anders behandelt, en hoe je over dat verschil heen leidt.",
    time: "10 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["cross-cultural"],
  },
  {
    id: "building-trust-cultures",
    slug: "building-trust-across-cultures",
    title: "Building Trust Across Cultures",
    titleId: "Membangun Kepercayaan Lintas Budaya",
    titleNl: "Vertrouwen Opbouwen over Culturen",
    description: "How trust is formed, earned, and lost differently in high- and low-context cultures.",
    descriptionId: "Bagaimana kepercayaan dibentuk, diperoleh, dan hilang secara berbeda dalam budaya konteks tinggi dan rendah.",
    descriptionNl: "Hoe vertrouwen anders wordt opgebouwd, verdiend en verloren in hoge- en lage-contextculturen.",
    time: "11 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["cross-cultural"],
  },
  {
    id: "giving-feedback-across-cultures",
    slug: "giving-feedback-across-cultures",
    title: "Giving Feedback Across Cultures",
    titleId: "Memberikan Umpan Balik Lintas Budaya",
    titleNl: "Feedback Geven over Culturen",
    description: "Why feedback lands so differently depending on cultural context — and a framework for giving honest, constructive feedback across high- and low-context cultures.",
    descriptionId: "Mengapa umpan balik diterima sangat berbeda tergantung konteks budaya — dan kerangka untuk memberikan umpan balik yang jujur dan konstruktif.",
    descriptionNl: "Waarom feedback zo anders aankomt afhankelijk van culturele context — en een raamwerk voor eerlijke, constructieve feedback over culturen heen.",
    time: "13 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["cross-cultural", "team-facilitation"],
  },
  {
    id: "ladder-of-inference",
    slug: "ladder-of-inference",
    title: "The Ladder of Inference",
    titleId: "Tangga Inferensi",
    titleNl: "De Ladder van Inferentie",
    description: "Most conflicts and misunderstandings start at the top of the Ladder — where we act on beliefs formed from incomplete data. Learn to trace your thinking back to the ground floor.",
    descriptionId: "Sebagian besar konflik dimulai di puncak Tangga — di mana kita bertindak berdasarkan keyakinan dari data yang tidak lengkap. Pelajari cara menelusuri kembali pemikiran Anda.",
    descriptionNl: "De meeste conflicten beginnen bovenaan de Ladder — waar we handelen op overtuigingen gevormd uit onvolledige data. Leer je denken terug te traceren naar de begane grond.",
    time: "12 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["thinking-tools", "cross-cultural"],
  },
  {
    id: "understanding-high-context",
    slug: "understanding-high-context",
    title: "Understanding High-Context Cultures",
    titleId: "Memahami Budaya Konteks Tinggi",
    titleNl: "Hoge-Contextculturen Begrijpen",
    description: "How communication styles shape relationships — and what that means for cross-cultural teams.",
    descriptionId: "Bagaimana gaya komunikasi membentuk hubungan — dan apa artinya bagi tim lintas budaya.",
    descriptionNl: "Hoe communicatiestijlen relaties vormen — en wat dat betekent voor interculturele teams.",
    time: "9 min",
    format: "Article",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["cross-cultural"],
  },
  {
    id: "returning-well",
    slug: "returning-well",
    title: "Returning Well: Life After Cross-Cultural Work",
    titleId: "Kembali dengan Baik: Kehidupan Setelah Pelayanan Lintas Budaya",
    titleNl: "Goed Terugkeren: Leven Na Interculturele Dienst",
    description: "Processing the transition back to your home culture after long-term cross-cultural service.",
    descriptionId: "Memproses transisi kembali ke budaya asal Anda setelah pelayanan lintas budaya jangka panjang.",
    descriptionNl: "De overgang verwerken naar je thuiscultuur na langdurige interculturele dienst.",
    time: "15 min",
    format: "Article",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["personal-development", "cross-cultural"],
  },
  // ── LEADERSHIP ─────────────────────────────────────────────────────────────
  {
    id: "leadership-altitudes",
    slug: "leadership-altitudes",
    title: "Leadership Altitudes",
    titleId: "Ketinggian Kepemimpinan",
    titleNl: "Leiderschapshoogten",
    description: "Understand the five altitude levels of leadership — from Team Member to International Organization — and learn to lead with perspective, trust, and strategic clarity.",
    descriptionId: "Pahami lima tingkat ketinggian kepemimpinan — dari Anggota Tim hingga Organisasi Internasional — dan pelajari cara memimpin dengan perspektif, kepercayaan, dan kejelasan strategis.",
    descriptionNl: "Begrijp de vijf leiderschapsniveaus — van Teamlid tot Internationale Organisatie — en leer leiden met perspectief, vertrouwen en strategische helderheid.",
    time: "15 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["leadership"],
  },
  {
    id: "servant-leadership",
    slug: "servant-leadership",
    title: "Servant Leadership",
    titleId: "Kepemimpinan Hamba",
    titleNl: "Dienend Leiderschap",
    description: "The biblical model of leading from below. Why the greatest leaders serve first — and what that looks like in cross-cultural ministry and organisational life.",
    descriptionId: "Model alkitabiah memimpin dari bawah. Mengapa pemimpin terbesar melayani terlebih dahulu — dan seperti apa dalam pelayanan lintas budaya dan kehidupan organisasi.",
    descriptionNl: "Het bijbelse model van leiden van onderaf. Waarom de grootste leiders eerst dienen — en hoe dat eruitziet in interculturele bediening en organisatieleven.",
    time: "12 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["leadership", "faith-calling"],
  },
  {
    id: "vision-casting",
    slug: "vision-casting",
    title: "Vision Casting",
    titleId: "Menebar Visi",
    titleNl: "Visie Uitdragen",
    description: "What compelling vision looks like — and how to communicate direction so clearly that people not only understand it, but move. Cross-cultural vision communication included.",
    descriptionId: "Seperti apa visi yang memikat — dan cara mengomunikasikan arah dengan begitu jelas sehingga orang tidak hanya memahaminya, tetapi bergerak. Termasuk komunikasi visi lintas budaya.",
    descriptionNl: "Hoe een overtuigende visie eruitziet — en hoe je richting zo helder communiceert dat mensen het niet alleen begrijpen, maar ook in beweging komen. Inclusief interculturele visiecommunicatie.",
    time: "12 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["leadership"],
  },
  {
    id: "managing-up",
    slug: "managing-up",
    title: "Managing Up",
    titleId: "Mengelola ke Atas",
    titleNl: "Omhoog Managen",
    description: "How to lead your leader well — understanding their needs, communicating upward effectively, and building the kind of trust that creates space for your own leadership to flourish.",
    descriptionId: "Cara memimpin pemimpin Anda dengan baik — memahami kebutuhan mereka, berkomunikasi ke atas secara efektif, dan membangun kepercayaan yang memberi ruang bagi kepemimpinan Anda sendiri.",
    descriptionNl: "Hoe je je leider goed leidt — hun behoeften begrijpen, effectief opwaarts communiceren, en vertrouwen opbouwen dat ruimte creëert voor jouw eigen leiderschap.",
    time: "11 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["leadership"],
  },
  {
    id: "raising-next-generation",
    slug: "raising-next-generation",
    title: "Raising Up the Next Generation",
    titleId: "Membesarkan Generasi Berikutnya",
    titleNl: "De Volgende Generatie Opleiden",
    description: "The multiplication principle: how to identify, invest in, and release the next generation of leaders — drawn from the Paul-Timothy model and real-world practice.",
    descriptionId: "Prinsip multiplikasi: cara mengidentifikasi, berinvestasi, dan melepaskan generasi pemimpin berikutnya — berdasarkan model Paulus-Timotius dan praktik nyata.",
    descriptionNl: "Het vermenigvuldigingsprincipe: hoe je de volgende generatie leiders identificeert, in investeert en vrijlaat — gebaseerd op het Paulus-Timotheüsmodel en praktijkervaring.",
    time: "13 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["leadership", "faith-calling"],
  },
  {
    id: "storytelling-leadership",
    slug: "storytelling-leadership",
    title: "Storytelling for Leaders",
    titleId: "Bercerita untuk Pemimpin",
    titleNl: "Storytelling voor Leiders",
    description: "Data informs. Stories move. Learn the structure of a compelling leadership story — and how to use narrative to cast vision, build culture, and connect across cultural lines.",
    descriptionId: "Data memberi informasi. Cerita menggerakkan. Pelajari struktur kisah kepemimpinan yang memikat — dan cara menggunakan narasi untuk menebarkan visi dan membangun budaya.",
    descriptionNl: "Data informeert. Verhalen bewegen. Leer de structuur van een overtuigend leiderschapsverhaal — en hoe je narratief gebruikt om visie uit te dragen en cultuur te bouwen.",
    time: "12 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["leadership"],
  },
  {
    id: "influential-leadership-framework",
    slug: "influential-leadership-framework",
    title: "The Influential Leadership Framework",
    titleId: "Kerangka Kepemimpinan Berpengaruh",
    titleNl: "Het Invloedrijk Leiderschapsraamwerk",
    description: "A systematic approach to leading with influence across cultural boundaries.",
    descriptionId: "Pendekatan sistematis untuk memimpin dengan pengaruh di lintas batas budaya.",
    descriptionNl: "Een systematische aanpak om met invloed te leiden over culturele grenzen heen.",
    time: "18 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["leadership"],
  },
  // ── TEAM & FACILITATION ────────────────────────────────────────────────────
  {
    id: "team-health",
    slug: "team-health",
    title: "Team Health Assessment",
    titleId: "Penilaian Kesehatan Tim",
    titleNl: "Teamgezondheid Tes",
    description: "How to diagnose the health of your team before problems become crises. Signs of dysfunction, markers of health, and practical steps toward a stronger team culture.",
    descriptionId: "Cara mendiagnosis kesehatan tim sebelum masalah menjadi krisis. Tanda-tanda disfungsi, penanda kesehatan, dan langkah praktis menuju budaya tim yang lebih kuat.",
    descriptionNl: "Hoe de gezondheid van je team te diagnosticeren voordat problemen crises worden. Tekenen van disfunctie, markers van gezondheid, en praktische stappen naar een sterkere teamcultuur.",
    time: "14 min",
    format: "Assessment",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["team-facilitation"],
  },
  {
    id: "six-thinking-hats",
    slug: "six-thinking-hats",
    title: "Six Thinking Hats",
    titleId: "Enam Topi Berpikir",
    titleNl: "Zes Denkhoeden",
    description: "Edward de Bono's framework for parallel thinking. Separate facts, emotions, caution, optimism, creativity, and process — so your team thinks together without conflict.",
    descriptionId: "Kerangka berpikir paralel Edward de Bono. Pisahkan fakta, emosi, kewaspadaan, optimisme, kreativitas, dan proses — agar tim Anda berpikir bersama tanpa konflik.",
    descriptionNl: "Edward de Bono's raamwerk voor parallel denken. Scheid feiten, emoties, voorzichtigheid, optimisme, creativiteit en proces — zodat je team samen denkt zonder conflict.",
    time: "12 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["team-facilitation", "thinking-tools"],
  },
  {
    id: "red-light-green-light",
    slug: "red-light-green-light",
    title: "Red Light & Green Light Thinking",
    titleId: "Pemikiran Lampu Merah & Lampu Hijau",
    titleNl: "Rood Licht & Groen Licht Denken",
    description: "A facilitation framework for separating creative idea generation (Green Light) from critical evaluation and decision-making (Red Light) — helping teams think more freely and decide more clearly.",
    descriptionId: "Kerangka fasilitasi untuk memisahkan generasi ide kreatif (Lampu Hijau) dari evaluasi kritis dan pengambilan keputusan (Lampu Merah) — membantu tim berpikir lebih bebas dan memutuskan lebih jelas.",
    descriptionNl: "Een facilitatieraamwerk voor het scheiden van creatieve ideeëngeneratie (Groen Licht) van kritische evaluatie en besluitvorming (Rood Licht) — helpt teams vrijer te denken en duidelijker te beslissen.",
    time: "10 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["team-facilitation", "thinking-tools"],
  },
  {
    id: "conflict-resolution-multicultural",
    slug: "conflict-resolution",
    title: "Conflict Resolution in Multicultural Teams",
    titleId: "Resolusi Konflik dalam Tim Multikultural",
    titleNl: "Conflictoplossing in Multiculturele Teams",
    description: "Why conflict looks different across cultures — and how to navigate it constructively.",
    descriptionId: "Mengapa konflik terlihat berbeda lintas budaya — dan cara menavigasinya secara konstruktif.",
    descriptionNl: "Waarom conflict er anders uitziet over culturen heen — en hoe je het constructief navigeert.",
    time: "14 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["team-facilitation", "cross-cultural"],
  },
  {
    id: "attention-retention",
    slug: "attention-retention",
    title: "Attention & Retention",
    titleId: "Perhatian & Retensi",
    titleNl: "Aandacht & Retentie",
    description: "Understand how attention and retention work in adult learning. Apply evidence-based principles to design training that sticks — across any culture or context.",
    descriptionId: "Pahami cara kerja perhatian dan retensi dalam pembelajaran orang dewasa. Terapkan prinsip berbasis bukti untuk merancang pelatihan yang berkesan — di budaya dan konteks apa pun.",
    descriptionNl: "Begrijp hoe aandacht en retentie werken in volwassenenleren. Pas evidencebased principes toe om training te ontwerpen die blijft hangen — in elke cultuur of context.",
    time: "14 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["team-facilitation"],
  },
  {
    id: "debriefing-reflection",
    slug: "debriefing-reflection",
    title: "Debriefing & Reflection",
    titleId: "Debriefing & Refleksi",
    titleNl: "Debriefing & Reflectie",
    description: "Leaders who don't reflect repeat their mistakes. A structured approach to debriefing experiences — individually and with your team — so that every season produces learning.",
    descriptionId: "Pemimpin yang tidak berefleksi mengulangi kesalahan mereka. Pendekatan terstruktur untuk mendebrifing pengalaman — secara individu dan bersama tim — agar setiap musim menghasilkan pembelajaran.",
    descriptionNl: "Leiders die niet reflecteren herhalen hun fouten. Een gestructureerde aanpak voor het debriefing van ervaringen — individueel en met je team — zodat elk seizoen leren oplevert.",
    time: "12 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["team-facilitation", "personal-development"],
  },
  {
    id: "above-below-the-line",
    slug: "above-below-the-line",
    title: "Above & Below the Line",
    titleId: "Di Atas & Di Bawah Garis",
    titleNl: "Boven & Onder de Lijn",
    description: "Are you leading as a Victor or a Victim? Recognize reactive patterns — blame, excuse, denial — and choose ownership, accountability, and responsibility instead.",
    descriptionId: "Apakah Anda memimpin sebagai Victor atau Victim? Kenali pola reaktif — menyalahkan, beralasan, menyangkal — dan pilih kepemilikan, akuntabilitas, dan tanggung jawab.",
    descriptionNl: "Leid je als Victor of als Slachtoffer? Herken reactieve patronen — beschuldiging, excuses, ontkenning — en kies in plaats daarvan eigenaarschap, verantwoordelijkheid.",
    time: "10 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["team-facilitation", "personal-development"],
  },
  // ── PERSONAL DEVELOPMENT ───────────────────────────────────────────────────
  {
    id: "comfort-zone",
    slug: "escaping-the-comfort-zone",
    title: "Escaping the Comfort Zone",
    titleId: "Keluar dari Zona Nyaman",
    titleNl: "Ontsnappen aan de Comfortzone",
    description: "Identify where your comfort zone ends and growth begins. Understand the four zones — Comfort, Fear, Learning, and Growth — and take steps toward meaningful change.",
    descriptionId: "Identifikasi di mana zona nyaman Anda berakhir dan pertumbuhan dimulai. Pahami empat zona — Nyaman, Takut, Belajar, dan Pertumbuhan — dan ambil langkah menuju perubahan yang bermakna.",
    descriptionNl: "Identificeer waar je comfortzone eindigt en groei begint. Begrijp de vier zones — Comfort, Angst, Leren en Groei — en zet stappen naar zinvolle verandering.",
    time: "12 min",
    format: "Worksheet",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["personal-development"],
  },
  {
    id: "fixed-growth-mindset",
    slug: "fixed-growth-mindset",
    title: "Fixed vs. Growth Mindset",
    titleId: "Mentalitas Tetap vs. Berkembang",
    titleNl: "Vaste vs. Groeimentaliteit",
    description: "Based on Carol Dweck's landmark research — compare how fixed and growth mindsets respond to challenges, obstacles, skills, effort, and the success of others. Then shift yours.",
    descriptionId: "Berdasarkan penelitian penting Carol Dweck — bandingkan cara mentalitas tetap dan berkembang merespons tantangan, hambatan, keterampilan, dan kesuksesan orang lain. Lalu ubah milik Anda.",
    descriptionNl: "Gebaseerd op Carol Dwecks baanbrekende onderzoek — vergelijk hoe vaste en groeimentaliteiten reageren op uitdagingen, obstakels, vaardigheden en het succes van anderen. Verschuif dan de jouwe.",
    time: "15 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["personal-development"],
  },
  {
    id: "smart-goals",
    slug: "smart-goals",
    title: "SMART Goals",
    titleId: "SMART Goals",
    titleNl: "SMART-doelen",
    description: "A five-part framework for setting goals that actually get done — Specific, Motivated, Achievable, Relevant, and Trackable. With built-in corrective actions: Clarify, Reframe, or Negotiate.",
    descriptionId: "Kerangka lima bagian untuk menetapkan tujuan yang benar-benar tercapai — Spesifik, Termotivasi, Dapat Dicapai, Relevan, dan Terukur. Dengan tindakan korektif bawaan.",
    descriptionNl: "Een vijfdelig raamwerk voor het stellen van doelen die daadwerkelijk worden bereikt — Specifiek, Gemotiveerd, Haalbaar, Relevant en Traceerbaar. Met ingebouwde correctieve acties.",
    time: "15 min",
    format: "Worksheet",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["personal-development"],
  },
  {
    id: "overcoming-procrastination",
    slug: "overcoming-procrastination",
    title: "Overcoming Procrastination",
    titleId: "Mengatasi Penundaan",
    titleNl: "Uitstellen Overwinnen",
    description: "Procrastination isn't laziness — it's usually fear, perfectionism, or overwhelm in disguise. A 5-step framework to identify your triggers, uncover root causes, and build momentum.",
    descriptionId: "Penundaan bukan kemalasan — biasanya rasa takut, perfeksionisme, atau kewalahan yang tersamar. Kerangka 5 langkah untuk mengidentifikasi pemicu, mengungkap akar penyebab, dan membangun momentum.",
    descriptionNl: "Uitstelgedrag is geen luiheid — het is meestal angst, perfectionisme of overweldiging in vermomming. Een 5-stapsraamwerk om je triggers te identificeren en momentum op te bouwen.",
    time: "30 min",
    format: "Worksheet",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["personal-development"],
  },
  {
    id: "emotional-intelligence",
    slug: "emotional-intelligence",
    title: "Emotional Intelligence (EQ)",
    titleId: "Kecerdasan Emosional (EQ)",
    titleNl: "Emotionele Intelligentie (EQ)",
    description: "Daniel Goleman's five components of EQ — self-awareness, self-regulation, motivation, empathy, and social skills — and why they determine your effectiveness as a leader.",
    descriptionId: "Lima komponen EQ Daniel Goleman — kesadaran diri, regulasi diri, motivasi, empati, dan keterampilan sosial — dan mengapa mereka menentukan efektivitas Anda sebagai pemimpin.",
    descriptionNl: "Daniël Golemans vijf componenten van EQ — zelfbewustzijn, zelfregulatie, motivatie, empathie en sociale vaardigheden — en waarom ze je effectiviteit als leider bepalen.",
    time: "14 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["personal-development", "leadership"],
  },
  {
    id: "johari-window",
    slug: "johari-window",
    title: "The Johari Window",
    titleId: "Jendela Johari",
    titleNl: "Het Johari-raam",
    description: "A model for self-awareness and team trust. Map your Open, Blind, Hidden, and Unknown zones — and learn to grow through feedback and disclosure.",
    descriptionId: "Model untuk kesadaran diri dan kepercayaan tim. Petakan zona Terbuka, Buta, Tersembunyi, dan Tidak Dikenal Anda — dan pelajari cara bertumbuh melalui umpan balik dan keterbukaan.",
    descriptionNl: "Een model voor zelfbewustzijn en teamvertrouwen. Breng je Open, Blinde, Verborgen en Onbekende zones in kaart — en leer groeien door feedback en openheid.",
    time: "12 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["personal-development"],
  },
  {
    id: "leaders-are-readers",
    slug: "leaders-are-readers",
    title: "Leaders Are Readers",
    titleId: "Pemimpin Adalah Pembaca",
    titleNl: "Leiders Zijn Lezers",
    description: "Great leaders commit to continuous learning. Discover why reading is a cornerstone of effective leadership and how to build a sustainable reading habit.",
    descriptionId: "Pemimpin hebat berkomitmen pada pembelajaran berkelanjutan. Temukan mengapa membaca adalah landasan kepemimpinan efektif dan cara membangun kebiasaan membaca yang berkelanjutan.",
    descriptionNl: "Grote leiders committeren zich aan continu leren. Ontdek waarom lezen een hoeksteen is van effectief leiderschap en hoe je een duurzame leesgewoonte opbouwt.",
    time: "10 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["personal-development"],
  },
  {
    id: "identity-under-pressure",
    slug: "identity-under-pressure",
    title: "Identity Under Pressure",
    titleId: "Identitas di Bawah Tekanan",
    titleNl: "Identiteit onder Druk",
    description: "Maintaining a grounded sense of self when living and leading between worlds.",
    descriptionId: "Mempertahankan rasa diri yang kuat saat hidup dan memimpin di antara dua dunia budaya.",
    descriptionNl: "Een gegronde identiteit bewaren terwijl je leeft en leidt tussen twee cultuurwerelden.",
    time: "10 min",
    format: "Article",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["faith-calling", "personal-development"],
  },
  // ── THINKING TOOLS ─────────────────────────────────────────────────────────
  {
    id: "decision-making",
    slug: "decision-making",
    title: "Decision Making Under Uncertainty",
    titleId: "Pengambilan Keputusan dalam Ketidakpastian",
    titleNl: "Beslissen onder Onzekerheid",
    description: "Frameworks for making wise decisions when you don't have all the information — especially in ambiguous, cross-cultural leadership contexts.",
    descriptionId: "Kerangka untuk membuat keputusan bijak ketika Anda tidak memiliki semua informasi — terutama dalam konteks kepemimpinan lintas budaya yang ambigu.",
    descriptionNl: "Raamwerken voor het nemen van wijze beslissingen wanneer je niet alle informatie hebt — vooral in ambigue, interculturele leiderschapscontexten.",
    time: "13 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["thinking-tools", "leadership"],
  },
  {
    id: "cognitive-biases",
    slug: "cognitive-biases",
    title: "Cognitive Biases in Leadership",
    titleId: "Bias Kognitif dalam Kepemimpinan",
    titleNl: "Cognitieve Vooroordelen in Leiderschap",
    description: "The mental shortcuts and blind spots that distort how every leader thinks — mapped and explained. Awareness is the first step toward clearer, more honest leadership.",
    descriptionId: "Jalan pintas mental dan titik buta yang mendistorsi cara setiap pemimpin berpikir — dipetakan dan dijelaskan. Kesadaran adalah langkah pertama menuju kepemimpinan yang lebih jelas dan jujur.",
    descriptionNl: "De mentale snelwegen en blinde vlekken die het denken van elke leider vertekenen — in kaart gebracht en uitgelegd. Bewustzijn is de eerste stap naar helderder en eerlijker leiderschap.",
    time: "10 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["thinking-tools"],
  },
  {
    id: "disc",
    slug: "disc",
    title: "DISC Personality Profile",
    titleId: "Profil Kepribadian DISC",
    titleNl: "DISC Persoonlijkheidsprofiel",
    description: "Understand your behavioural style and how it shapes the way you lead, communicate, and collaborate across cultures.",
    descriptionId: "Pahami gaya perilaku Anda dan bagaimana itu membentuk cara Anda memimpin, berkomunikasi, dan berkolaborasi lintas budaya.",
    descriptionNl: "Begrijp je gedragsstijl en hoe die de manier waarop je leidt, communiceert en samenwerkt over culturen heen vormt.",
    time: "10 min + quiz",
    format: "Assessment",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["leadership", "cross-cultural", "personal-development"],
  },
  {
    id: "three-thinking-styles",
    slug: "three-thinking-styles",
    title: "Three Thinking Styles",
    titleId: "Tiga Gaya Berpikir",
    titleNl: "Drie Denkstijlen",
    description: "Discover whether you lead with Conceptual, Holistic, or Intuitional thinking — and how to work across all three.",
    descriptionId: "Temukan apakah Anda memimpin dengan pemikiran Konseptual, Holistik, atau Intuitif — dan cara bekerja di antara ketiganya.",
    descriptionNl: "Ontdek of je leidt met Conceptueel, Holistisch of Intuïtief denken — en hoe je over alle drie kunt werken.",
    time: "15 min + quiz",
    format: "Assessment",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["thinking-tools"],
  },
  {
    id: "big-five",
    slug: "big-five",
    title: "The Big Five (OCEAN)",
    titleId: "Big Five (OCEAN)",
    titleNl: "De Big Five (OCEAN)",
    description: "The most scientifically validated personality framework in the world — five dimensions that predict how you lead, collaborate, adapt, and grow across every culture.",
    descriptionId: "Kerangka kepribadian paling tervalidasi secara ilmiah di dunia — lima dimensi yang memprediksi cara Anda memimpin, berkolaborasi, beradaptasi, dan bertumbuh di setiap budaya.",
    descriptionNl: "Het meest wetenschappelijk gevalideerde persoonlijkheidsraamwerk ter wereld — vijf dimensies die voorspellen hoe je leidt, samenwerkt, aanpast en groeit in elke cultuur.",
    time: "8–10 min",
    format: "Assessment",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["personal-development", "leadership", "cross-cultural"],
  },
  {
    id: "myers-briggs",
    slug: "myers-briggs",
    title: "Myers-Briggs Type Indicator (MBTI)",
    titleId: "Myers-Briggs Type Indicator (MBTI)",
    titleNl: "Myers-Briggs Type Indicator (MBTI)",
    description: "One of the most widely used personality frameworks in the world — rooted in Jungian psychology. Discover your type and what it means for how you lead, decide, and relate.",
    descriptionId: "Salah satu kerangka kepribadian yang paling banyak digunakan di dunia — berakar pada psikologi Jung. Temukan tipe Anda dan artinya bagi cara Anda memimpin, memutuskan, dan berhubungan.",
    descriptionNl: "Een van de meest gebruikte persoonlijkheidsraamwerken ter wereld — geworteld in de Jungiaanse psychologie. Ontdek je type en wat het betekent voor hoe je leidt, beslist en relateert.",
    time: "8–10 min",
    format: "Assessment",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["personal-development", "leadership", "cross-cultural"],
  },
  // ── FAITH & CALLING ────────────────────────────────────────────────────────
  {
    id: "sabbath-leadership",
    slug: "sabbath-leadership",
    title: "Sabbath & Sustainable Leadership",
    titleId: "Sabat & Kepemimpinan Berkelanjutan",
    titleNl: "Sabbat & Duurzaam Leiderschap",
    description: "Rest is a leadership discipline. Why sustainable leaders build rhythms of Sabbath — and how to practise it in high-demand cross-cultural environments.",
    descriptionId: "Istirahat adalah disiplin kepemimpinan. Mengapa pemimpin berkelanjutan membangun ritme Sabat — dan bagaimana mempraktikkannya dalam lingkungan lintas budaya yang penuh tuntutan.",
    descriptionNl: "Rust is een leiderschapsdiscipline. Waarom duurzame leiders ritmes van Sabbat opbouwen — en hoe je die beoefent in veeleisende interculturele omgevingen.",
    time: "11 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["faith-calling", "personal-development"],
  },
  {
    id: "leading-without-losing-faith",
    slug: "leading-without-losing-faith",
    title: "Leading Without Losing Your Faith",
    titleId: "Memimpin Tanpa Kehilangan Imanmu",
    titleNl: "Leidinggeven Zonder Je Geloof te Verliezen",
    description: "Maintaining spiritual rootedness when leadership demands are high and cultural confusion is real.",
    descriptionId: "Mempertahankan keberakaran rohani ketika tuntutan kepemimpinan tinggi dan kebingungan budaya nyata adanya.",
    descriptionNl: "Spiritueel geworteld blijven wanneer leiderschapseisen hoog zijn en culturele verwarring reëel is.",
    time: "10 min",
    format: "Article",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["faith-calling"],
  },
  // ── RESILIENCE & MENTAL HEALTH ─────────────────────────────────────────────
  {
    id: "understanding-burnout",
    slug: "understanding-burnout",
    title: "Understanding Burnout",
    titleId: "Memahami Kelelahan",
    titleNl: "Burnout Begrijpen",
    description: "The three types of burnout — overload, underchallenge, and neglect — and how to build the people, practices, and purpose that prevent it.",
    descriptionId: "Tiga jenis kelelahan — beban berlebih, kurang tantangan, dan diabaikan — dan cara membangun orang, praktik, dan tujuan yang mencegahnya.",
    descriptionNl: "De drie soorten burnout — overbelasting, onderprikkeling en verwaarlozing — en hoe je de mensen, praktijken en doelen bouwt die het voorkomen.",
    time: "12 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["personal-development", "faith-calling", "self-care"],
  },
  {
    id: "relational-longevity",
    slug: "relational-longevity",
    title: "Relational Longevity",
    titleId: "Kelanggengan Relasional",
    titleNl: "Relationele Longeviteit",
    description: "Why relational breakdown is the leading cause of premature departure — and how to build the interpersonal skills that keep teams together for the long haul.",
    descriptionId: "Mengapa kerusakan relasional adalah penyebab utama kepergian dini — dan bagaimana membangun keterampilan interpersonal yang menjaga tim tetap bersama dalam jangka panjang.",
    descriptionNl: "Waarom relationele afbraak de voornaamste oorzaak is van vroegtijdig vertrek — en hoe je de interpersoonlijke vaardigheden bouwt die teams voor de lange termijn bij elkaar houden.",
    time: "13 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["team-facilitation", "personal-development", "self-care"],
  },
  {
    id: "emotional-safety-families",
    slug: null,
    title: "Emotional Safety for Families",
    description: "Parental stress directly shapes children's wellbeing. How to build emotional safety at home — and model humility through relational repair.",
    time: "11 min",
    format: "Guide",
    languages: ["en"],
    gated: true,
    topics: ["personal-development", "faith-calling", "self-care"],
  },
  {
    id: "healthy-transitions",
    slug: null,
    title: "Healthy Transitions",
    description: "The RAFT model for navigating re-entry, role change, or any major life transition — Reconciliation, Affirmation, Farewells, Think Ahead.",
    time: "14 min",
    format: "Guide",
    languages: ["en"],
    gated: true,
    topics: ["personal-development", "cross-cultural", "self-care"],
  },
  {
    id: "psychological-first-aid",
    slug: "psychological-first-aid",
    title: "Psychological First Aid",
    titleId: "Pertolongan Pertama Psikologis",
    titleNl: "Psychologische Eerste Hulp",
    description: "Equipping leaders to support teammates in crisis. The RAPID model for immediate, compassionate intervention when things go wrong in the field.",
    descriptionId: "Membekali pemimpin untuk mendukung rekan tim dalam krisis. Model RAPID untuk intervensi segera dan penuh belas kasihan ketika hal-hal berjalan buruk di lapangan.",
    descriptionNl: "Leiders toerusten om teamleden in crisis te ondersteunen. Het RAPID-model voor onmiddellijke, meelevende interventie wanneer het mis gaat in het veld.",
    time: "12 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["team-facilitation", "personal-development", "self-care"],
  },
  {
    id: "sustainable-pace",
    slug: null,
    title: "Sustainable Pace",
    description: "Sabbath rhythms, personal health architecture, and the theology of rest. Practical resilience habits for leaders built to last.",
    time: "11 min",
    format: "Guide",
    languages: ["en"],
    gated: true,
    topics: ["personal-development", "faith-calling", "self-care"],
  },
];

export function getTopicResources(topicSlug: string): Resource[] {
  return RESOURCES.filter(r => r.topics.includes(topicSlug));
}

export function getTopicBySlug(slug: string): Topic | undefined {
  return TOPICS.find(t => t.slug === slug);
}

export const LANG_LABELS: Record<string, string> = {
  en: "EN",
  id: "ID",
  nl: "NL",
};
