export type ResourceFormat = "Article" | "Assessment" | "Worksheet" | "Guide";
export type Lang = "en" | "id" | "nl";

export type Resource = {
  id: string;
  slug: string | null;
  title: string;
  description: string;
  time: string;
  format: ResourceFormat;
  languages: Lang[];
  gated: boolean;
  topics: string[];
};

export type Topic = {
  slug: string;
  title: string;
  description: string;
  icon: string;
};

export const TOPICS: Topic[] = [
  {
    slug: "cross-cultural",
    title: "Cross-Cultural",
    description: "Navigating cultural difference — how to read, adapt, and lead across contexts without losing yourself.",
    icon: "M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2 2 2 0 012 2v2.945M8 3.935V5.5A2.5 2.5 0 0010.5 8h.5a2 2 0 012 2 2 2 0 104 0 2 2 0 012-2h1.064M15 20.488V18a2 2 0 012-2h3.064M21 12a9 9 0 11-18 0 9 9 0 0118 0z",
  },
  {
    slug: "leadership",
    title: "Leadership",
    description: "Frameworks and practices for leading with clarity, influence, and conviction — at every level.",
    icon: "M9 20l-5.447-2.724A1 1 0 013 16.382V5.618a1 1 0 011.447-.894L9 7m0 13l6-3m-6 3V7m6 10l4.553 2.276A1 1 0 0021 18.382V7.618a1 1 0 00-.553-.894L15 4m0 13V4m0 0L9 7",
  },
  {
    slug: "team-facilitation",
    title: "Team & Facilitation",
    description: "Tools for leading teams well — facilitation, conflict, health, feedback, and keeping groups moving forward.",
    icon: "M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0z",
  },
  {
    slug: "personal-development",
    title: "Personal Development",
    description: "Becoming more of who you are — mindset, habits, self-awareness, and sustainable growth.",
    icon: "M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253",
  },
  {
    slug: "thinking-tools",
    title: "Thinking Tools",
    description: "Frameworks that sharpen how you think, decide, and solve problems — especially under pressure.",
    icon: "M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z",
  },
  {
    slug: "faith-calling",
    title: "Faith & Calling",
    description: "Staying rooted in what matters most — the biblical foundations of leadership, identity, and purpose.",
    icon: "M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z",
  },
  {
    slug: "self-care",
    title: "Self-Care & Resilience",
    description: "Protecting your wellbeing — burnout prevention, mental health, healthy rhythms, and personal sustainability for the long haul.",
    icon: "M14.828 14.828a4 4 0 01-5.656 0M21 12a9 9 0 11-18 0 9 9 0 0118 0zm-9-4a1 1 0 11-2 0 1 1 0 012 0zm0 8a1 1 0 11-2 0 1 1 0 012 0z",
  },
];

export const RESOURCES: Resource[] = [
  // ── CROSS-CULTURAL ─────────────────────────────────────────────────────────
  {
    id: "cultural-intelligence",
    slug: "cultural-intelligence",
    title: "Cultural Intelligence (CQ)",
    description: "Understand the four dimensions of Cultural Intelligence — and how to develop the capacity to function effectively in any cultural context.",
    time: "14 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["cross-cultural"],
  },
  {
    id: "power-distance",
    slug: "power-distance",
    title: "Power Distance",
    description: "How authority, hierarchy, and respect are perceived differently across cultures — and what that means for how you lead, communicate, and make decisions.",
    time: "11 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["cross-cultural", "leadership"],
  },
  {
    id: "intercultural-communication",
    slug: "intercultural-communication",
    title: "Intercultural Communication",
    description: "High-context vs. low-context, direct vs. indirect — understanding how cultures communicate so you stop misreading the people you lead.",
    time: "13 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["cross-cultural"],
  },
  {
    id: "time-and-culture",
    slug: "time-and-culture",
    title: "Time & Culture",
    description: "Monochronic vs. polychronic time — why your team treats deadlines, meetings, and relationships very differently, and how to lead across that gap.",
    time: "10 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["cross-cultural"],
  },
  {
    id: "building-trust-cultures",
    slug: "building-trust-across-cultures",
    title: "Building Trust Across Cultures",
    description: "How trust is formed, earned, and lost differently in high- and low-context cultures.",
    time: "11 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["cross-cultural"],
  },
  {
    id: "giving-feedback-across-cultures",
    slug: "giving-feedback-across-cultures",
    title: "Giving Feedback Across Cultures",
    description: "Why feedback lands so differently depending on cultural context — and a framework for giving honest, constructive feedback across high- and low-context cultures.",
    time: "13 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["cross-cultural", "team-facilitation"],
  },
  {
    id: "ladder-of-inference",
    slug: "ladder-of-inference",
    title: "The Ladder of Inference",
    description: "Most conflicts and misunderstandings start at the top of the Ladder — where we act on beliefs formed from incomplete data. Learn to trace your thinking back to the ground floor.",
    time: "12 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["thinking-tools", "cross-cultural"],
  },
  {
    id: "understanding-high-context",
    slug: "understanding-high-context",
    title: "Understanding High-Context Cultures",
    description: "How communication styles shape relationships — and what that means for cross-cultural teams.",
    time: "9 min",
    format: "Article",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["cross-cultural"],
  },
  {
    id: "returning-well",
    slug: "returning-well",
    title: "Returning Well: Life After Cross-Cultural Work",
    description: "Processing the transition back to your home culture after long-term cross-cultural service.",
    time: "15 min",
    format: "Article",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["personal-development", "cross-cultural"],
  },
  // ── LEADERSHIP ─────────────────────────────────────────────────────────────
  {
    id: "leadership-altitudes",
    slug: "leadership-altitudes",
    title: "Leadership Altitudes",
    description: "Understand the five altitude levels of leadership — from Team Member to International Organization — and learn to lead with perspective, trust, and strategic clarity.",
    time: "15 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["leadership"],
  },
  {
    id: "servant-leadership",
    slug: "servant-leadership",
    title: "Servant Leadership",
    description: "The biblical model of leading from below. Why the greatest leaders serve first — and what that looks like in cross-cultural ministry and organisational life.",
    time: "12 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["leadership", "faith-calling"],
  },
  {
    id: "vision-casting",
    slug: "vision-casting",
    title: "Vision Casting",
    description: "What compelling vision looks like — and how to communicate direction so clearly that people not only understand it, but move. Cross-cultural vision communication included.",
    time: "12 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["leadership"],
  },
  {
    id: "managing-up",
    slug: "managing-up",
    title: "Managing Up",
    description: "How to lead your leader well — understanding their needs, communicating upward effectively, and building the kind of trust that creates space for your own leadership to flourish.",
    time: "11 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["leadership"],
  },
  {
    id: "raising-next-generation",
    slug: "raising-next-generation",
    title: "Raising Up the Next Generation",
    description: "The multiplication principle: how to identify, invest in, and release the next generation of leaders — drawn from the Paul-Timothy model and real-world practice.",
    time: "13 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["leadership", "faith-calling"],
  },
  {
    id: "storytelling-leadership",
    slug: "storytelling-leadership",
    title: "Storytelling for Leaders",
    description: "Data informs. Stories move. Learn the structure of a compelling leadership story — and how to use narrative to cast vision, build culture, and connect across cultural lines.",
    time: "12 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["leadership"],
  },
  {
    id: "influential-leadership-framework",
    slug: "influential-leadership-framework",
    title: "The Influential Leadership Framework",
    description: "A systematic approach to leading with influence across cultural boundaries.",
    time: "18 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["leadership"],
  },
  // ── TEAM & FACILITATION ────────────────────────────────────────────────────
  {
    id: "team-health",
    slug: "team-health",
    title: "Team Health Assessment",
    description: "How to diagnose the health of your team before problems become crises. Signs of dysfunction, markers of health, and practical steps toward a stronger team culture.",
    time: "14 min",
    format: "Assessment",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["team-facilitation"],
  },
  {
    id: "six-thinking-hats",
    slug: "six-thinking-hats",
    title: "Six Thinking Hats",
    description: "Edward de Bono's framework for parallel thinking. Separate facts, emotions, caution, optimism, creativity, and process — so your team thinks together without conflict.",
    time: "12 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["team-facilitation", "thinking-tools"],
  },
  {
    id: "red-light-green-light",
    slug: "red-light-green-light",
    title: "Red Light & Green Light Thinking",
    description: "A facilitation framework for separating creative idea generation (Green Light) from critical evaluation and decision-making (Red Light) — helping teams think more freely and decide more clearly.",
    time: "10 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["team-facilitation", "thinking-tools"],
  },
  {
    id: "conflict-resolution-multicultural",
    slug: "conflict-resolution",
    title: "Conflict Resolution in Multicultural Teams",
    description: "Why conflict looks different across cultures — and how to navigate it constructively.",
    time: "14 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["team-facilitation", "cross-cultural"],
  },
  {
    id: "attention-retention",
    slug: "attention-retention",
    title: "Attention & Retention",
    description: "Understand how attention and retention work in adult learning. Apply evidence-based principles to design training that sticks — across any culture or context.",
    time: "14 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["team-facilitation"],
  },
  {
    id: "debriefing-reflection",
    slug: "debriefing-reflection",
    title: "Debriefing & Reflection",
    description: "Leaders who don't reflect repeat their mistakes. A structured approach to debriefing experiences — individually and with your team — so that every season produces learning.",
    time: "12 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["team-facilitation", "personal-development"],
  },
  {
    id: "above-below-the-line",
    slug: "above-below-the-line",
    title: "Above & Below the Line",
    description: "Are you leading as a Victor or a Victim? Recognize reactive patterns — blame, excuse, denial — and choose ownership, accountability, and responsibility instead.",
    time: "10 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["team-facilitation", "personal-development"],
  },
  // ── PERSONAL DEVELOPMENT ───────────────────────────────────────────────────
  {
    id: "comfort-zone",
    slug: "escaping-the-comfort-zone",
    title: "Escaping the Comfort Zone",
    description: "Identify where your comfort zone ends and growth begins. Understand the four zones — Comfort, Fear, Learning, and Growth — and take steps toward meaningful change.",
    time: "12 min",
    format: "Worksheet",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["personal-development"],
  },
  {
    id: "fixed-growth-mindset",
    slug: "fixed-growth-mindset",
    title: "Fixed vs. Growth Mindset",
    description: "Based on Carol Dweck's landmark research — compare how fixed and growth mindsets respond to challenges, obstacles, skills, effort, and the success of others. Then shift yours.",
    time: "15 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["personal-development"],
  },
  {
    id: "smart-goals",
    slug: "smart-goals",
    title: "SMART Goals",
    description: "A five-part framework for setting goals that actually get done — Specific, Motivated, Achievable, Relevant, and Trackable. With built-in corrective actions: Clarify, Reframe, or Negotiate.",
    time: "15 min",
    format: "Worksheet",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["personal-development"],
  },
  {
    id: "overcoming-procrastination",
    slug: "overcoming-procrastination",
    title: "Overcoming Procrastination",
    description: "Procrastination isn't laziness — it's usually fear, perfectionism, or overwhelm in disguise. A 5-step framework to identify your triggers, uncover root causes, and build momentum.",
    time: "30 min",
    format: "Worksheet",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["personal-development"],
  },
  {
    id: "emotional-intelligence",
    slug: "emotional-intelligence",
    title: "Emotional Intelligence (EQ)",
    description: "Daniel Goleman's five components of EQ — self-awareness, self-regulation, motivation, empathy, and social skills — and why they determine your effectiveness as a leader.",
    time: "14 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["personal-development", "leadership"],
  },
  {
    id: "johari-window",
    slug: "johari-window",
    title: "The Johari Window",
    description: "A model for self-awareness and team trust. Map your Open, Blind, Hidden, and Unknown zones — and learn to grow through feedback and disclosure.",
    time: "12 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["personal-development"],
  },
  {
    id: "leaders-are-readers",
    slug: "leaders-are-readers",
    title: "Leaders Are Readers",
    description: "Great leaders commit to continuous learning. Discover why reading is a cornerstone of effective leadership and how to build a sustainable reading habit.",
    time: "10 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["personal-development"],
  },
  {
    id: "identity-under-pressure",
    slug: "identity-under-pressure",
    title: "Identity Under Pressure",
    description: "Maintaining a grounded sense of self when living and leading between worlds.",
    time: "10 min",
    format: "Article",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["faith-calling", "personal-development"],
  },
  // ── THINKING TOOLS ─────────────────────────────────────────────────────────
  {
    id: "decision-making",
    slug: "decision-making",
    title: "Decision Making Under Uncertainty",
    description: "Frameworks for making wise decisions when you don't have all the information — especially in ambiguous, cross-cultural leadership contexts.",
    time: "13 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["thinking-tools", "leadership"],
  },
  {
    id: "cognitive-biases",
    slug: "cognitive-biases",
    title: "Cognitive Biases in Leadership",
    description: "The mental shortcuts and blind spots that distort how every leader thinks — mapped and explained. Awareness is the first step toward clearer, more honest leadership.",
    time: "10 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["thinking-tools"],
  },
  {
    id: "disc",
    slug: "disc",
    title: "DISC Personality Profile",
    description: "Understand your behavioural style and how it shapes the way you lead, communicate, and collaborate across cultures.",
    time: "10 min + quiz",
    format: "Assessment",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["leadership", "cross-cultural", "personal-development"],
  },
  {
    id: "three-thinking-styles",
    slug: "three-thinking-styles",
    title: "Three Thinking Styles",
    description: "Discover whether you lead with Conceptual, Holistic, or Intuitional thinking — and how to work across all three.",
    time: "15 min + quiz",
    format: "Assessment",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["thinking-tools"],
  },
  {
    id: "big-five",
    slug: "big-five",
    title: "The Big Five (OCEAN)",
    description: "The most scientifically validated personality framework in the world — five dimensions that predict how you lead, collaborate, adapt, and grow across every culture.",
    time: "8–10 min",
    format: "Assessment",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["personal-development", "leadership", "cross-cultural"],
  },
  {
    id: "myers-briggs",
    slug: "myers-briggs",
    title: "Myers-Briggs Type Indicator (MBTI)",
    description: "One of the most widely used personality frameworks in the world — rooted in Jungian psychology. Discover your type and what it means for how you lead, decide, and relate.",
    time: "8–10 min",
    format: "Assessment",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["personal-development", "leadership", "cross-cultural"],
  },
  // ── FAITH & CALLING ────────────────────────────────────────────────────────
  {
    id: "sabbath-leadership",
    slug: "sabbath-leadership",
    title: "Sabbath & Sustainable Leadership",
    description: "Rest is a leadership discipline. Why sustainable leaders build rhythms of Sabbath — and how to practise it in high-demand cross-cultural environments.",
    time: "11 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: false,
    topics: ["faith-calling", "personal-development"],
  },
  {
    id: "leading-without-losing-faith",
    slug: "leading-without-losing-faith",
    title: "Leading Without Losing Your Faith",
    description: "Maintaining spiritual rootedness when leadership demands are high and cultural confusion is real.",
    time: "10 min",
    format: "Article",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["faith-calling"],
  },
  // ── RESILIENCE & MENTAL HEALTH ─────────────────────────────────────────────
  {
    id: "understanding-burnout",
    slug: "understanding-burnout",
    title: "Understanding Burnout",
    description: "The three types of burnout — overload, underchallenge, and neglect — and how to build the people, practices, and purpose that prevent it.",
    time: "12 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["personal-development", "faith-calling", "self-care"],
  },
  {
    id: "relational-longevity",
    slug: "relational-longevity",
    title: "Relational Longevity",
    description: "Why relational breakdown is the leading cause of premature departure — and how to build the interpersonal skills that keep teams together for the long haul.",
    time: "13 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["team-facilitation", "personal-development", "self-care"],
  },
  {
    id: "emotional-safety-families",
    slug: null,
    title: "Emotional Safety for Families",
    description: "Parental stress directly shapes children's wellbeing. How to build emotional safety at home — and model humility through relational repair.",
    time: "11 min",
    format: "Guide",
    languages: ["en"],
    gated: true,
    topics: ["personal-development", "faith-calling", "self-care"],
  },
  {
    id: "healthy-transitions",
    slug: null,
    title: "Healthy Transitions",
    description: "The RAFT model for navigating re-entry, role change, or any major life transition — Reconciliation, Affirmation, Farewells, Think Ahead.",
    time: "14 min",
    format: "Guide",
    languages: ["en"],
    gated: true,
    topics: ["personal-development", "cross-cultural", "self-care"],
  },
  {
    id: "psychological-first-aid",
    slug: "psychological-first-aid",
    title: "Psychological First Aid",
    description: "Equipping leaders to support teammates in crisis. The RAPID model for immediate, compassionate intervention when things go wrong in the field.",
    time: "12 min",
    format: "Guide",
    languages: ["en", "id", "nl"],
    gated: true,
    topics: ["team-facilitation", "personal-development", "self-care"],
  },
  {
    id: "sustainable-pace",
    slug: null,
    title: "Sustainable Pace",
    description: "Sabbath rhythms, personal health architecture, and the theology of rest. Practical resilience habits for leaders built to last.",
    time: "11 min",
    format: "Guide",
    languages: ["en"],
    gated: true,
    topics: ["personal-development", "faith-calling", "self-care"],
  },
];

export function getTopicResources(topicSlug: string): Resource[] {
  return RESOURCES.filter(r => r.topics.includes(topicSlug));
}

export function getTopicBySlug(slug: string): Topic | undefined {
  return TOPICS.find(t => t.slug === slug);
}

export const LANG_LABELS: Record<string, string> = {
  en: "EN",
  id: "ID",
  nl: "NL",
};
